### ISSUE TITLE
Support query parameters for pre-filled tags

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#1011]
In the interest of supporting Pulse for the organization of events, we should have the ability to direct users to an "add submission" URL in which one or more tags are automatically applied to the submission.

Suggested approach: `https://mozillapulse.org/add?tag=foo,bar,baz` results in a page where the tags `foo`,`bar`, and `baz` are pre-filled in the tags field.

"Probably a good idea to have" features:
* Only auto-fill the tags if they already exist in the tag database
* Tags pre-filled due to query string are unable to be removed from the "tag selection" field, but the submitter can add more. (Continued ability to add more tags is more important than preventing removal of pre-filled ones)

Building this will help meet the needs of this year's sprint/internet health month.

cc @acabunoc @zee-moz @xmatthewx @gideonthomas

**Comment by gideonthomas** [comment]
@alanmoo to determine if this a "nice to have" or a core requirement:

People who are not logged in, when they hit that url should be redirected to the pulse login page and once they login, they should be redirected to the `/add?tags=...` page.
Setting that as the redirect path should be easy (requires a backend env var change). The only small caveat is if they need to verify their email with Github, they will not be redirected to the `add?tags=...` page ([filed here](https://github.com/mozilla/network-pulse-api/issues/416)). But I think this can be easily addressed with copy in the CTA.

**Comment by alanmoo** [comment]
Great point. This is probably more important than the other "good to have" features.

**Comment by alanmoo** [comment]
@gideonthomas It looks like this already works when logging in using Google and Github. So the only thing I haven't tested is email verification with Github- is that because it comes in as a different request?

**Comment by gideonthomas** [comment]
@alanmoo the only thing that won't work is redirecting to the page you were on. Currently it will redirect you to the pulse homepage. Re: the github verification thing - I'm not sure why, but the simple answer is django-allauth has not implemented it.

**Comment by alanmoo** [comment]
I still don't understand. This works:

![login-forwarding-pulse](https://user-images.githubusercontent.com/1682681/53200325-4570ff80-35ef-11e9-8625-117af6b59919.gif)

**Comment by gideonthomas** [comment]
oh interesting...ignore me then :P

**Comment by Pomax** [comment]
PR up on https://github.com/mozilla/network-pulse/pull/1015, I didn't see an easy to way to filter out "non-existent tags" and so it didn't seem worth trying to figure out.

**Comment by xmatthewx** [comment]
Let's think about whether we need a tag field like `program_tag`, separate from `tags`. 

This feature is still very useful ... for use during mozfest for example. For the fellow proposal use case, however, I think we need more separation. Otherwise, users could submit stuff via main form using a tag that appears in autocomplete, sidestepping proper workflow.

**Comment by gideonthomas** [comment]
@xmatthewx given the timeline for the global sprint work, should we create a new project brief (might also involve minor design work) for this? I think (sorry if I'm just repeating what you're saying) we can probably scope them as two separate features:
1. A network member runs a hackathon and wants every participant to create a pulse project with a preset tag. The feature implemented above will enable the network member (who doesn't have admin access) to share a url to a pre-filled form. Based on the requirements above (and the time constraints), this might suffice for the Global Sprint.
2. Open Leadership (or Fellowships, or even MozFest for example) is accepting new proposals for their program. As a staff-driven program they can create an "initiative" via the admin that shows a form that collects proposal information and is auto-tagged with the specific initiative (controlled via the admin so a user cannot change it). This would need a new project brief.

**Comment by xmatthewx** [comment]
Yes that's a great description of two different use cases. 

For the initiative case, I think we can still leverage a URL parameter - I don't think we need to secure it, we just don't want collision with user selected tags.

**Comment by alanmoo** [comment]
That second case starts to get awfully close to the type of thing Salesforce is meant for.

**Comment by Pomax** [comment]
echoing @alanmoo, the first case makes sense as something we should support, but the second case sounds dangerously close to "pulse is not the right tool for that job".

**Comment by gideonthomas** [comment]
Can this be closed?

Re: your concerns above - one thing missing from my user story is a way for the network to view and show interest in some way for proposals to make the proposal process open. This is where pulse can be powerful and where salesforce cannot be used based on our internal instance constraints.
Either way, we can discuss more once a new brief is filed.

**Comment by Pomax** [comment]
that is probably worth having as a separate discussion, aside from the functionality of having an `add/?tags=...` url as available option for folks who want to funnel users into pulse.

**Comment by alanmoo** [comment]
+1, Pomax. This has landed. Let's file another ticket for other discussions if they need to continue.
