### ISSUE TITLE
Likes should be a list view instead of cards

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#70]
Luke has pointed out that the Likes list could get very long so we should show a list view instead of the full card.

This is a great idea but seems post MVP since it will involve styling a secondary card style and will have more extra functionality to expand the condensed content...

**Comment by kristinashu** [comment]
Mocked this up https://redpen.io/p/nzcd35d57dd04ad6dc

<img width="316" alt="screen shot 2016-11-23 at 3 39 41 pm" src="https://cloud.githubusercontent.com/assets/1068783/20582124/185dd352-b193-11e6-8ffc-9b2f90e01aac.png">

**Comment by xmatthewx** [comment]
Nice. 

Would be good with small thumbnails, but probably doesn't work since they don't all have thumbnails.

**Comment by aayushsanghavi** [comment]
I'd like to take this issue

**Comment by ryanwarsaw** [comment]
Hey @aayushsanghavi! I just wanted to give you a heads up, Mozilla Foundation is currently on winter break until January 3rd, and this project is currently being converted to a React project.

You may want to wait for these changes to land before you tackle this, or alternatively if you want to get started immediately, you could try and make your changes off of the react branch. Just note there will likely be not a lot of people around in the event you need help, until after the New Year.

It's awesome that you'd like to contribute, if you have any questions let me know. Cheers!

**Comment by aayushsanghavi** [comment]
Okay but I've already fixed the issue on my local master branch and I don't know react, so is it fine if I made a PR for this issue (on the master branch) and one of the contributors could make appropriate changes to make it work in react.

**Comment by ryanwarsaw** [comment]
@aayushsanghavi Definitely file a pull request if you've already made the changes, I wouldn't be able to answer your second question, but I don't see any problem with doing that. Just as long as this issue remains open, we should be fine. 🎉

**Comment by mmmavis** [comment]
@ryanwarsaw thanks for taking care of the repo and contributors while most of us were away! 👍 

@kristinashu should we include heart icon in each list item so users can unfav things from the favs page as well?

@aayushsanghavi I'm going to review your PR now 😃

**Comment by kristinashu** [comment]
Yes, very good idea @mmmavis! I've opened a new ticket for it https://github.com/mozilla/network-pulse/issues/288

**Comment by mmmavis** [comment]
This is done now: https://mozilla.github.io/network-pulse/ Thanks @aayushsanghavi !
